const API_BASE_URL = ["127.0.0.1", "localhost"].includes(window.location.hostname)
  ? "http://127.0.0.1:8000"
  : "https://sust-final.onrender.com";
const state = { agents: [], providers: [], positions: new Map(), alerts: [], cases: [], initialized: false };
const session = JSON.parse(sessionStorage.getItem("agentflow_demo_session") || "{}");
const providerCode = session.providerCode || "nagad_sim";
const $ = (selector) => document.querySelector(selector);
const money = (value) => `৳ ${Number(value || 0).toLocaleString("en-BD", { maximumFractionDigits: 0 })}`;
const providerLabel = (code) => ({ bkash_sim: "bKash", nagad_sim: "Nagad", rocket_sim: "Rocket" }[code] || code);

async function api(path, options = {}) { const response = await fetch(`${API_BASE_URL}${path}`, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || `API request failed (${response.status})`); } return response.json(); }
function setApiStatus(kind, text) { const node = $("#apiStatus"); node.className = `api-status ${kind}`; node.innerHTML = `<i></i> ${text}`; }
function showError(message) { $("#errorBanner").textContent = message; $("#errorBanner").hidden = false; }
function toast(message) { const node = $("#toast"); node.textContent = message; node.hidden = false; setTimeout(() => { node.hidden = true; }, 3800); }
function selectedProvider() { return $("#providerFilter").value; }
function inScopeAgents() { const area = $("#areaFilter").value; return state.agents.filter((agent) => area === "all" || agent.area === area); }
function positionFor(agentId, provider) { return (state.positions.get(agentId) || []).find((position) => position.provider_code === provider); }
function agentName(id) { return state.agents.find((agent) => agent.id === id)?.name || `Agent ${id}`; }

function seedFilters() { const areaValue = $("#areaFilter").value; const selected = state.providers.find((provider) => provider.code === providerCode); $("#providerFilter").innerHTML = selected ? `<option value="${selected.code}">${selected.display_name}</option>` : "<option>Provider unavailable</option>"; $("#areaFilter").innerHTML = `<option value="all">All areas</option>${[...new Set(state.agents.map((a) => a.area))].map((area) => `<option value="${area}">${area}</option>`).join("")}`; $("#areaFilter").value = [...$("#areaFilter").options].some((o) => o.value === areaValue) ? areaValue : "all"; const label = selected?.display_name || providerLabel(providerCode); $("#providerContext").textContent = `${label.toUpperCase()} · SYNTHETIC PROVIDER OPERATIONS`; $("#providerHeading").textContent = `${label} liquidity coordination`; $("#providerDescription").textContent = `This workspace shows only ${label} routed alerts and ${label} e-money positions, alongside shared physical cash needed for coordination.`; document.title = `${label} operations | AgentFlow`; state.initialized = true; }
function riskFor(agent, provider) { const position = positionFor(agent.id, provider); const activeAlert = state.alerts.some((alert) => alert.agent_id === agent.id && alert.provider_code === provider && alert.status !== "resolved"); return Boolean(activeAlert || agent.cash_requires_attention || position?.requires_attention || position?.forecast.confidence === "low"); }

function renderSummary() { const provider = selectedProvider(); const scope = inScopeAgents(); const alerts = filteredAlerts(); const risk = scope.filter((agent) => provider !== "all" && riskFor(agent, provider)); const cases = state.cases.filter((item) => provider === "all" || item.provider_code === provider); $("#agentCount").textContent = scope.length; $("#agentCountHint").textContent = `${provider === "all" ? "All providers" : providerLabel(provider)} · selected area`; $("#openAlertCount").textContent = alerts.filter((alert) => alert.status !== "resolved").length; $("#openAlertHint").textContent = "Routed to provider operations"; $("#riskAgentCount").textContent = risk.length; $("#riskAgentHint").textContent = provider === "all" ? "Choose a provider to prioritise" : `${providerLabel(provider)} or shared-cash attention`; $("#caseCount").textContent = cases.length; $("#caseCountHint").textContent = `${cases.filter((item) => item.status === "proposed").length} awaiting confirmation`; }
function renderAgents() { const provider = selectedProvider(); const scope = inScopeAgents(); $("#agentGrid").innerHTML = scope.map((agent) => { const position = positionFor(agent.id, provider); const attention = riskFor(agent, provider); const reason = agent.cash_requires_attention ? "Shared physical cash is inside the backend operational attention zone." : position?.forecast.confidence === "low" ? "Provider balance needs verification." : position?.requires_attention ? `${providerLabel(provider)} e-money is inside the backend operational attention zone.` : "No immediate threshold issue."; return `<article class="agent-card ${attention ? "attention" : ""}"><div class="agent-head"><div><h3>${agent.name}</h3><p>Agent ${agent.id} · ${agent.area}</p></div><span class="chip ${attention ? "attention" : "good"}">${attention ? "attention" : "stable"}</span></div><div class="agent-numbers"><div><span>Shared cash</span><strong>${money(agent.shared_cash)}</strong><small>Safety ${money(agent.cash_threshold)}</small></div><div><span>${providerLabel(provider)} e-money</span><strong>${position ? money(position.balance) : "—"}</strong><small>Safety ${position ? money(position.safety_threshold) : "—"}</small></div></div><p class="agent-foot">${reason}</p></article>`; }).join("") || `<div class="empty">No agents match the selected area.</div>`; }
function filteredAlerts() { const provider = selectedProvider(); const status = $("#alertFilter").value; const scope = new Set(inScopeAgents().map((agent) => agent.id)); return state.alerts.filter((alert) => scope.has(alert.agent_id) && (provider === "all" || alert.provider_code === provider) && (status === "all" || alert.status === status)); }
function renderAlerts() { const alerts = filteredAlerts(); $("#alertCounter").textContent = alerts.length; $("#alertList").innerHTML = alerts.length ? alerts.map((alert) => `<article class="alert ${alert.status}"><div class="alert-top"><span class="status ${alert.status}">${alert.status}</span><span class="chip">${providerLabel(alert.provider_code)}</span><span class="chip">Agent ${alert.agent_id}</span></div><h3>${alert.title}</h3><p><strong>Recipient:</strong> ${alert.recipient} · <strong>Owner:</strong> ${alert.owner}</p><p style="margin-top:6px"><strong>Evidence:</strong> ${alert.evidence}</p><p style="margin-top:6px"><strong>Next step:</strong> ${alert.recommended_action}</p>${alert.status !== "resolved" ? `<button class="mini-button" data-plan-alert="${alert.id}">Use in support proposal</button>` : ""}</article>`).join("") : `<div class="empty">No routed alerts match these filters.</div>`; }
function renderProposalOptions() { const requester = $("#requesterSelect").value; const supporter = $("#supporterSelect").value; const alert = $("#alertSelect").value; $("#requesterSelect").innerHTML = state.agents.map((agent) => `<option value="${agent.id}">${agent.name} · ${agent.area}</option>`).join(""); $("#supporterSelect").innerHTML = state.agents.map((agent) => `<option value="${agent.id}">${agent.name} · ${agent.area}</option>`).join(""); const selected = state.providers.find((provider) => provider.code === providerCode); $("#proposalProvider").innerHTML = `<option value="${providerCode}">${selected?.display_name || providerLabel(providerCode)}</option>`; const availableAlerts = state.alerts.filter((item) => item.status !== "resolved"); $("#alertSelect").innerHTML = `<option value="">No linked alert</option>${availableAlerts.map((item) => `<option value="${item.id}">#${item.id} · Agent ${item.agent_id} · ${item.title}</option>`).join("")}`; const primaryAlert = availableAlerts.find((item) => item.agent_id === 1) || availableAlerts[0]; const candidate = state.agents.find((agent) => agent.id === 2) || state.agents[1]; $("#requesterSelect").value = requester || (primaryAlert ? String(primaryAlert.agent_id) : "1"); $("#supporterSelect").value = supporter || String(candidate?.id || 2); $("#proposalProvider").value = providerCode; $("#alertSelect").value = alert || (primaryAlert ? String(primaryAlert.id) : ""); updatePreview(); }
function updatePreview() { const requester = Number($("#requesterSelect").value); const supporter = Number($("#supporterSelect").value); const provider = $("#proposalProvider").value; const amount = Number($("#amountInput").value || 0); const requesterPosition = positionFor(requester, provider); const supporterPosition = positionFor(supporter, provider); const safe = requester !== supporter && amount > 0 && (state.agents.find((agent) => agent.id === requester)?.shared_cash || 0) >= amount && (supporterPosition?.balance || 0) - amount >= (supporterPosition?.safety_threshold || Infinity); $("#exchangePreview").innerHTML = `<strong>Proposed same-provider support:</strong><br>${agentName(requester)} provides <strong>${money(amount)} physical cash</strong> to ${agentName(supporter)}. After human confirmation, ${agentName(supporter)} contributes <strong>${money(amount)} ${providerLabel(provider)} e-money</strong> to ${agentName(requester)} in this local simulation.<br><br><strong>${safe ? "Safety checks currently pass." : "Safety check does not pass: choose a different amount or supporting agent."}</strong> No balance changes when you create the proposal.`; }
function renderCases() { const provider = selectedProvider(); const cases = state.cases.filter((item) => provider === "all" || item.provider_code === provider); $("#caseList").innerHTML = cases.length ? cases.map((item) => `<article class="case"><div class="case-top"><span class="status ${item.status}">${item.status}</span><span class="chip">${providerLabel(item.provider_code)}</span>${item.alert_id ? `<span class="chip">Alert #${item.alert_id}</span>` : ""}</div><h3>${agentName(item.requester_agent_id)} ↔ ${agentName(item.supporting_agent_id)}</h3><p>${money(item.cash_amount)} physical cash from requester; equal ${providerLabel(item.provider_code)} e-money from supporting agent.</p><p style="margin-top:5px">${item.note ? `<strong>Note:</strong> ${item.note}` : "Awaiting explicit provider confirmation; no simulated balance has changed."}</p>${item.status === "proposed" ? `<div class="case-actions"><button class="button primary" data-complete-case="${item.id}">Confirm completion</button><button class="button secondary" data-cancel-case="${item.id}">Cancel</button></div>` : ""}</article>`).join("") : `<div class="empty">No support cases for the selected provider.</div>`; }
function renderAll() { renderSummary(); renderAgents(); renderAlerts(); renderCases(); }
async function refresh() { $("#errorBanner").hidden = true; setApiStatus("", "Refreshing live data…"); try { const [agents, providers, cases] = await Promise.all([api("/agents"), api("/providers"), api(`/provider-coordination?provider_code=${providerCode}`)]); const agentData = await Promise.all(agents.map(async (agent) => [agent.id, await api(`/positions?agent_id=${agent.id}&provider_code=${providerCode}`), await api(`/alerts?agent_id=${agent.id}&provider_code=${providerCode}&include_resolved=true`)])); state.agents = agents; state.providers = providers; state.cases = cases; state.positions = new Map(agentData.map(([id, positions]) => [id, positions])); state.alerts = agentData.flatMap(([id, , alerts]) => alerts.map((alert) => ({ ...alert, agent_id: id }))); seedFilters(); renderProposalOptions(); renderAll(); $("#updatedAt").textContent = `Last refreshed ${new Date().toLocaleTimeString()}`; setApiStatus("ready", "Live API connected"); } catch (error) { setApiStatus("error", "API connection failed"); showError(`${error.message} Start the backend on port 8000, then refresh.`); } }
async function createProposal(event) { event.preventDefault(); try { const alertId = $("#alertSelect").value; const result = await api("/provider-coordination/proposals", { method: "POST", body: JSON.stringify({ provider_code: $("#proposalProvider").value, requester_agent_id: Number($("#requesterSelect").value), supporting_agent_id: Number($("#supporterSelect").value), alert_id: alertId ? Number(alertId) : null, cash_amount: Number($("#amountInput").value), e_money_amount: Number($("#amountInput").value) }) }); toast(`Support case #${result.id} created. No balance changed.`); await refresh(); } catch (error) { showError(error.message); } }
async function updateCase(caseId, payload) { await api(`/provider-coordination/${caseId}`, { method: "PATCH", body: JSON.stringify(payload) }); await refresh(); }
$("#areaFilter").addEventListener("change", renderAll); $("#alertFilter").addEventListener("change", renderAlerts); ["#requesterSelect", "#supporterSelect", "#proposalProvider", "#amountInput"].forEach((selector) => $(selector).addEventListener("input", updatePreview)); $("#proposalForm").addEventListener("submit", createProposal); $("#refreshButton").addEventListener("click", refresh); $("#resetButton").addEventListener("click", async () => { if (!window.confirm("Reset all synthetic demo data? This permanently clears completed support cases and their history records.")) return; try { await api("/demo/reset", { method: "POST" }); toast("Synthetic data reset. All support cases cleared."); await refresh(); } catch (error) { showError(error.message); } }); $("#alertList").addEventListener("click", (event) => { const id = event.target.dataset.planAlert; if (!id) return; const alert = state.alerts.find((item) => item.id === Number(id)); $("#alertSelect").value = id; $("#requesterSelect").value = String(alert.agent_id); const candidate = state.agents.find((agent) => agent.id === 2) || state.agents.find((agent) => agent.id !== alert.agent_id); $("#supporterSelect").value = String(candidate.id); updatePreview(); $("#planner").scrollIntoView({ behavior: "smooth", block: "start" }); }); $("#caseList").addEventListener("click", async (event) => { const cancel = event.target.dataset.cancelCase; const complete = event.target.dataset.completeCase; try { if (cancel) { await updateCase(cancel, { status: "cancelled" }); toast("Support proposal cancelled. No balance changed."); } if (complete) { const item = state.cases.find((item) => item.id === Number(complete)); $("#confirmDialog").dataset.caseId = complete; $("#confirmationNote").value = ""; $("#confirmCopy").textContent = `This will update only synthetic local balances for ${agentName(item.requester_agent_id)} and ${agentName(item.supporting_agent_id)}. It will also resolve its linked alert if present.`; $("#confirmDialog").showModal(); } } catch (error) { showError(error.message); } }); $("#confirmCaseButton").addEventListener("click", async (event) => { event.preventDefault(); const note = $("#confirmationNote").value.trim(); if (!note) { $("#confirmCopy").textContent = "A human confirmation note is required."; return; } try { await updateCase($("#confirmDialog").dataset.caseId, { status: "completed", note }); $("#confirmDialog").close(); toast("Synthetic support completed and linked alert updated."); } catch (error) { showError(error.message); } }); $("#signOutButton").addEventListener("click", () => { sessionStorage.removeItem("agentflow_demo_session"); window.location.assign("login.html"); });
if (JSON.parse(sessionStorage.getItem("agentflow_demo_session") || "{}").role === "agent") window.location.replace("agent_dashboard.html"); refresh();
